home_study/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('study.urls')),
    path('admin/', admin.site.urls),
]

study/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.user_login, name="login"),
    path("logout", views.user_logout, name="logout"),
    path("day/<int:id>", views.get_day, name="day"),
    path("day/<int:day_id>/lesson/add", views.add_lesson, name="add_lesson"),
    path("day/create", views.create_day, name="create_day"),
    path("day/<int:day_id>/update", views.update_day, name="update_day"),
    path("day/<int:day_id>/delete", views.delete_day, name="delete_day"),
    path("lesson/get", views.get_lesson, name="get_lesson"),
    path("lesson/update", views.update_lesson, name="update_lesson"),
    path("lesson/delete", views.delete_lesson, name="delete_lesson"),
    path("subject", views.all_subjects, name="subjects"),
    path("subject/<int:subject_id>", views.subject, name="subject"),
    path("subject/create", views.create_subject, name="create_subject")
    
]

study/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime

class Day(models.Model):
    date = models.DateField(
        'Study day',
        default=datetime.date.today,
        unique=True
        )

    def __str__(self) -> str:
        return str(self.date)

class Subject(models.Model):
    title = models.CharField(
        'Subject title',
        max_length=200,
        unique=True
    )
    teacher = models.ForeignKey(User, on_delete=models.PROTECT)
    def __str__(self) -> str:
        return self.title

class Lesson(models.Model):
    subject = models.ForeignKey(
        Subject, 
        on_delete=models.PROTECT)
    description = models.TextField('Lesson description')
    home_work = models.TextField('Home work')
    grade = models.IntegerField('Studen\'s grade for lesson',
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        blank=True,
        null=True)
    day = models.ForeignKey(Day, on_delete=models.PROTECT)

    def __str__(self) -> str:
        return f"{str(self.day)}_{str(self.subject)}"

templates/day/change.html
{% extends "base.html" %}

{% block content%}
<div class="container">
    <div class="row justify-content-center">
        <form class="border col" action="{% url 'change_day' day_id=day_id%}">
            <div class="d-flex justify-content-center">
                <label for="id_date">Дата:</label>
                <input type="date" name="date" value="2021-12-03" required="" id="id_date">
                <div class="d-flex mx-2">
                    <input class="button btn btn-warning" type="submit" value="Изменить"/>
                    <a href="{% url 'change_day' day_id=day_id %}" class="button btn btn-secondary">Отмена</a>
                </div>
            </div> 
        </form>
    </div>
</div>
{% endblock %}

templates/day/day.html
{% extends "base.html" %}

{% block title %}
{{ day.date | date:'d-m-Y' }}
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-4">

      <div class="d-flex flex-column">
        <div class="d-flex flex-column border rounded mb-2 p-2 shadow-sm">
          <div>
            <p class="text-center fw-bold">Изменить</p>
          </div>
          <div class="d-flex justify-content-center">
            {% if user.is_authenticated %}
            <button id="changeDayBtn" class="btn btn-warning mx-2" date="{{day.date|date:'Y-m-d'}}">Изменить</button>
            <button id="deleteDayBtn" class="btn btn-danger mx-2" day="{{ day.id }}">Удалить</button>
            {% else %}
            <button id="changeDayBtn" class="btn btn-warning mx-2" date="{{day.date|date:'Y-m-d'}}" disabled>Изменить</button>
            <button id="deleteDayBtn" class="btn btn-danger mx-2" day="{{ day.id }}" disabled>Удалить</button>
            {% endif %}

            <!-- Modal Update date of day -->
            <div id="updateDayModal" class="modal fade" tabindex="-1">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Изменение даты</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <input id="dayDateModal" type="date" name="dayDateModal">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="dayUpdateBtn" day={{day.id}}>Обновить</button>
                  </div>
                </div>
              </div>
            </div>
            
          </div>
        </div>

        <div class="col border rounded p-2 shadow-sm">
          <p class="text-center fw-bold">Добавить занятие</p>
          <form id="addLesson" action="">
            {% csrf_token %}
            <div class="form-group">
              <label for="subjectInput">Предмет</label>
              <select id="subjectInput" class="form-control" name="subject">
                {% for subject in subjects %}
                {% if forloop.counter == 1 %}
                <option selected>{{ subject.title }}</option>
                {% else %}
                <option>{{ subject.title }}</option>
                {% endif %}
                {% endfor %}
              </select>
            </div>
            <div class="form-group">
              <label for="descriptionInput">Описание</label>
              <textarea class="form-control" id="descriptionInput" name="description" rows="3"></textarea>
            </div>
            <div class="form-group">
              <label for="homeWorkInput">Домашнее задание</label>
              <textarea class="form-control" id="homeWorkInput" name="homework" rows="2"></textarea>
            </div>
            <div class="form-group">
              <label for="gradeInput">Оценка</label>
              <select id="gradeInput" class="form-control" name="grade">
                <option selected></option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </div>
            {% if user.is_authenticated %}
            <button type="submit" class="btn btn-success form-control">Добавить</button>
            {% else %}
            <button type="submit" class="btn btn-success form-control" disabled>Добавить</button>
            {% endif %}
          </form>
        </div>
      </div>
      
    </div>

    <div class="col-7 border rounded p-2 shadow-sm">
      <p class="text-center fw-bold">Занятия</p>
      <table class="table table-hover" id="lessonsTable">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Предмет</th>
            <th scope="col">Домашннее задание</th>
            <th scope="col">Оценка</th>
            <th scope="col">Дествия</th>
          </tr>
        </thead>
        <tbody>
        {% for lesson in lessons %}
          <tr id="{{lesson.id}}">
            <th scope="row" name="index">{{ forloop.counter }}</th>
            <td name="subject">{{lesson.subject}}</td>
            <td name="homework">{{lesson.home_work}}</td>
            <td name="grade">{% if lesson.grade %}{{lesson.grade}}{% else %}{% endif %}</td>
            {% if user.is_authenticated %}
            <td>
                <button type="button" id="editBtn" lesson="{{lesson.id}}" class="btn btn-warning"><i class="fas fa-edit"></i></button>
                <button id="delLesson" lesson="{{lesson.id}}" type="button" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
            </td>
            {% else %}
            <td>
                <button type="button" id="editBtn" lesson="{{lesson.id}}" class="btn btn-warning"  disabled><i class="fas fa-edit"></i></button>
                <button id="delLesson" lesson="{{lesson.id}}" type="button" class="btn btn-danger" disabled><i class="fas fa-trash-alt"></i></button>
            </td>
            {% endif %}
          </tr>
        {% endfor %}
        </tbody>
      </table>
      
      <!-- Modal -->
      <div class="modal fade" id="editLesson" tabindex="-1" aria-labelledby="editLessonLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Изменение урока</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <form id="edirLessonModal" action="">
                {% csrf_token %}
                <div class="form-group">
                  <label for="subjectInputModal">Предмет</label>
                  <select id="subjectInputModal" class="form-control" name="subjectInputModal">
                    {% for subject in subjects %}
                    <option>{{ subject.title }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="form-group">
                  <label for="descriptionInputModal">Описание</label>
                  <textarea class="form-control" id="descriptionInputModal" name="description" rows="3"></textarea>
                </div>
                <div class="form-group">
                  <label for="homeWorkInputModal">Домашнее задание</label>
                  <textarea class="form-control" id="homeWorkInputModal" name="homework" rows="2"></textarea>
                </div>
                <div class="form-group">
                  <label for="gradeInputModal">Оценка</label>
                  <select id="gradeInputModal" class="form-control" name="gradeInputModal">
                    <option selected></option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                  </select>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отменить</button>
              <button type="button" id="updateLessonModal" class="btn btn-warning">Обновить</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script>

//Open modal Update day
$('#changeDayBtn').click(function(){
  let date = $(this).attr('date');
  document.getElementById("dayDateModal").valueAsDate = new Date(date)
  $('#updateDayModal').modal('show');
})

// Update day
$('#dayUpdateBtn').click(function() {
  let date = $('#dayDateModal').val().trim();
  const csrftoken = getCookie('csrftoken');
  
  $.ajax({
    url: "{% url 'update_day' day_id=day.id %}",
    method: "PUT",
    headers: { 
      'X-CSRFToken': csrftoken
    },
    data: {
      "date": date
    },
    success: function(data) {
      if (!data.error)
      $('#updateDayModal').modal('hide');
      $('#changeDayBtn').attr('date', date);
    }
  });
  return false;
})

// Delete day
$('#deleteDayBtn').click(function(){
  const csrftoken = getCookie('csrftoken');
  let action = confirm("Вы уверены, что хотите удалить день?");
  if (action) {
    $.ajax({
      url: "{% url 'delete_day' day_id=day.id %}",
      method: "DELETE",
      headers: { 
        'X-CSRFToken': csrftoken
      },
      success: function(data) {
        if (!data.error) {
          window.location.replace('/');
        }
      }
    });
    return false;
  }
})

// Add lesson
$("form#addLesson").submit(function() {
  var subjectInput = $('select[name="subject"]').val().trim();
  var descriptionInput = $('textarea[name="description"]').val().trim();
  var homeworkInput = $('textarea[name="homework"]').val().trim();
  var gradeInput = $('select[name="grade"]').val().trim();
  const csrftoken = getCookie('csrftoken');
  
  if (subjectInput && descriptionInput) {
      // Create Ajax Call
      $.ajax({
          url: "{% url 'add_lesson' day_id=day.id %}",
          method: "POST",
          headers: { 
            'X-CSRFToken': csrftoken
          },
          data: {
              'subject': subjectInput,
              'description': descriptionInput,
              'homework': homeworkInput,
              'grade': gradeInput
          },
          dataType: 'json',
          success: function (data) {
              if (data.lesson) {
                appendToLessonTable(data.lesson);
                $('tbody > tr').each(function(index, tr) { 
                  tr.cells[0].innerHTML = index + 1;
                });
              }
          }
      });
    } else {
      alert("All fields must have a valid value.");
  }
  $('form#addLesson').trigger("reset");
  return false;
});

function appendToLessonTable(lesson) {
  var tableRef = document.getElementById('lessonsTable').getElementsByTagName('tbody')[0];
  if (!lesson.grade) {
    lesson.grade = ""
  };
  var rowData = `<th scope="row">${tableRef.rows.length+1}</th>
  <td>${lesson.subject}</td>
  <td>${lesson.home_work}</td>
  <td>${lesson.grade}</td>
  {% if user.is_authenticated %}
  <td>
      <button id="editBtn" type="button" lesson="${lesson.id}" class="btn btn-warning"><i class="fas fa-edit"></i></button>
      <button id="delLesson" lesson="${lesson.id}" type="button" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
  </td>
  {% else %}
  <td>
      <button id="editBtn" lesson="${lesson.id}" type="button" class="btn btn-warning" disabled><i class="fas fa-edit"></i></button>
      <button id="delLesson" lesson="${lesson.id}" type="button" class="btn btn-danger" disabled><i class="fas fa-trash-alt"></i></button>
  </td>
  {% endif %}`
  var newRow = tableRef.insertRow(tableRef.rows.length);
  newRow.innerHTML = rowData;
}

// Delete lesson
$('tbody').on('click', '#delLesson', function() {
  let id = $(this).attr('lesson');
  const csrftoken = getCookie('csrftoken');
  data = {
    "lesson_id": id
  };
  mythis = this;
  var action = confirm("Вы уверены, что хотите удалить урок?");
  if (action) {
    $.ajax({
      url: "{% url 'delete_lesson' %}",
      method: "POST",
      headers: { 
        'X-CSRFToken': csrftoken
      },
      data: data,
      success: function(data){
        if (data.deleted) {
          $(mythis).closest('tr').remove();
          $('tbody > tr').each(function(index, tr) { 
            tr.cells[0].innerHTML = index + 1;
          }); 
        }
      }
    })
  };
})

// Get lesson for update
$('tbody').on('click', '#editBtn', function() {
  let id = $(this).attr('lesson');
  $.ajax({
    url: "{% url 'get_lesson' %}",
    method: "GET",
    data: {"lesson_id": id},
    success: function(data) {
      if (data) {
        $('#subjectInputModal').val(data.subject)
        $('#descriptionInputModal').val(data.description)
        $('#homeWorkInputModal').val(data.homework)
        $('#gradeInputModal').val(data.grade)
        $('#updateLessonModal').attr('lesson', data.lesson_id)
        $('#updateLessonModal').attr('day', data.day)
        $('#editLesson').modal('show');
      }
    }
  })
})

// Update lesson
$('#updateLessonModal').click(function() {
  const csrftoken = getCookie('csrftoken');
  let lesson_data = {
    "lesson_id": $('#updateLessonModal').attr('lesson'),
    "subject": $('#subjectInputModal').val().trim(),
    "description": $('#descriptionInputModal').val().trim(),
    "home_work": $('#homeWorkInputModal').val().trim(),
    "grade": $('#gradeInputModal').val().trim(),
    "day_id": $('#updateLessonModal').attr('day')
  }
  $.ajax({
    url: "{% url 'update_lesson' %}",
    method: "POST",
    dataType: 'json',
    data: JSON.stringify(lesson_data),
    headers: {
      'X-CSRFToken': csrftoken,
      'Content-Type': 'application/json'
    },
    contentType: 'application/json',
    success: function(data) {
      if (!data.error) {
        $(`table#lessonsTable #${data.lesson}`).children().each(function() {
          attr = $(this).attr('name')
          if (attr === 'subject') {
            $(this).text(lesson_data.subject)
          }
          if (attr === 'homework') {
            $(this).text(lesson_data.home_work)
          }
          if (attr === 'grade') {
            $(this).text(lesson_data.grade)
          }
        })
      }
    }
  })
  $('form#edirLessonModal').trigger("reset");
  $('#editLesson').modal('hide');

  return false;
})


</script>
{% endblock %}